//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationJECRC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIG()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string EmailID { get; set; }
        public int BranchID { get; set; }
        public int internsNbr { get; set; }
        public Nullable<int> LetterAlloted { get; set; }
        public Nullable<int> Applied { get; set; }
        public Nullable<int> Stipened { get; set; }
        public Nullable<int> NoFeesNoStippend { get; set; }
        public Nullable<int> StudentPaid { get; set; }
        public Nullable<int> Confirmed { get; set; }
        public int LoginID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
    }
}
