//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationJECRC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JECRCEntities : DbContext
    {
        public JECRCEntities()
            : base("name=JECRCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<FIG> FIG { get; set; }
        public virtual DbSet<FIG_Coor> FIG_Coor { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<University_FIG_Coor> University_FIG_Coor { get; set; }

        public System.Data.Entity.DbSet<WebApplicationJECRC.Models.FIGBranchCoorModel> FIGBranchCoorModels { get; set; }
    }
}
