//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationJECRC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Student
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Name { get; set; }

        [DisplayName("Email ID")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "This field is required")]
        public string EmailID { get; set; }

        [DisplayName("Registration Number")]
        [Required(ErrorMessage = "This field is required")]
        public string RegNumber { get; set; }

        [DisplayName("Branch Name")]
        [Required(ErrorMessage = "This field is required")]
        public int BranchID { get; set; }

        [DisplayName("Parent Mobile Number")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "This field is required")]
        public string ParentMobilenNumber { get; set; }

        [DisplayName("Do you Have an alloted letter?")]
        [Required(ErrorMessage = "This field is required")]
        public Nullable<bool> LetterAlloted { get; set; }

        [DisplayName("Did you applied for internship?")]
        [Required(ErrorMessage = "This field is required")]
        public Nullable<bool> HasApplied { get; set; }

        [DisplayName("If yes,Will you get paid?")]
        public Nullable<bool> IsPaid { get; set; }

        [DisplayName("If yes, Please write your salary")]
        
        public string Amount { get; set; }

        public int OrganiID { get; set; }

        [DisplayName("FIG Name")]
        [Required(ErrorMessage = "This field is required")]
        public int FigID { get; set; }

        public int LoginID { get; set; }

        [NotMapped]
        public List<Branch> BranchCollection { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual FIG FIG { get; set; }
        public virtual Login Login { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
